---
title: "Landscape Ecology and Species Distribution Modelling"
author: "Anoob Prakash"
date: "8 February 2019"
output: pdf_document
---

How do organisms interact with the landscape? 


This question is the focus of a vast amount of research effort globally, but the following are some notable examples to give the general idea:

Patches: species may prefer a certain kind of habitat, for example mature woodland, or ponds. Individuals of the species of concern may not be able to breed or feed outside of this type of habitat. The habitat thus defines the patch.

Matrix: If one land use dominates the landscape, that landuse forms the matrix, e.g. arable land in eastern England. If the dominant land use is uniformly inhospitable, organisms become isolated in patches of suitable habitat. For example, some characteristic plants of ancient woodland cannot survive in arable fields, and do not have seeds equipped with a mechanism to disperse between isolated woodland fragments.

Corridors: There has been a lot of research and debate about the role of hedgerows as corridors for small woodland mammals and birds. Such species may be able to move between woodland habitat patches along hedgrerows, whereas they might not feel safe enough to cross an arable field.

Barriers: Roads, pipelines or fences might form barriers to movement of shy or less agile animals.

Mosaic: Lesser horseshoe bats are an example of an animal that needs to live in a landscape mosaic. They sleep in old trees in mature woodland, then fly along hedgerows to open, wet places where they hunt for flies.

***

`source`: https://bit.ly/2S8VCT6
