---
title: "Species Distribution Modelling"
author: "Anoob Prakash"
date: "2 February 2019"
output:
  pdf_document: default
  html_document: default
---

##Step 1: Expected outcomes

By the end of the lesson, students should be able to:

Understand the concepts of Landscape ecology and Species Distribution Modelling (SDM) and how it fits within the broader framework of landscape ecology. 

**Topics to be covered:**  

- Patch-corridor-matrix  

- Scientific principles of landscape ecology  

    - Fragmentation  
    - Structure and Function  
    - Connectivity  
    - Individual focal species  
    - Generic focal species  
  
  
- Applications and themes  

    - SLOSS tradeoffs  
    - Corridor linkage  
    - Inter-disciplinary studies  
  

- Species Distribution Modelling  

    - Cuurent trends  
    
        - $\Delta$TraitSDM  

##Step 2: Assessing outcomes

Students will be assessed through discussion.

##Step 3: Learning plan

  - New concepts regarding landscape ecology will be introduced and help them relate to the ones studied in the spatial ecology lectures.  
  - This might probably be review at this point of time for some. Try to understand the underlying concepts and the current trends in field.  
  - Learn why it evolved and how interdciplinary science and technological advances are helping it grow.
  - Try to answer some in-class questions and discuss various ideas within groups.


##Step 4: Reflections

**What went well:**  

  - A healthy discussion was initiated between students regarding various concepts taught in class. 
  
  - Covered a lot of the basic's required by the student's for taking up and learning landscape ecology and SDMs on thier own. 
  
  - Student's participated and helped in giving better explanation and examples for different topics and scenarios.  
  
**What could be improved:**  

  - Certain concepts was not clearly explained and was lacking in examples. Needs to get in more details (e.g. spatial autocorrelation). This could have been solved, if I had spend more time in less topics to cover.
  
  
  - There was a lack of cohesive flow and I unknowingly ommitted certain portions of the presentation. A properly ordered notes would have helped in conveying all the required info to the class.
  
  - More details about SDMs with simpler explantaions backed by explaining the individual elements of SDM.
  
  
**What would I do differently next time:**  
  
  - A more cohesive storyline approach with properly ordered notes to follow through.  
  
  - Simplify and explain with examples along with better use of the visual aid.  
  
  - Providing some materials for the students to go through before class help them understand the topics better and participate efficiently.  






